# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: テスト用コンテナをビルドして実行
        run: |
          docker compose -f docker-compose-test.yaml up \
            --build \
            --abort-on-container-exit \
            --exit-code-from app-test

      - name: テスト用コンテナを削除
        if: always()
        run: docker compose -f docker-compose-test.yaml down -v
